import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-between items-center p-4 gap-4 h-16">
            <Link href="/" className="text-xl font-bold">
              PROJECTPULSE
            </Link>
            
            <nav className="flex items-center gap-6">
              {/* <Link href="/about" className="hover:text-blue-500">
                About
              </Link> */}
              
              {/* Protected navigation items */}
              <SignedIn>
                <Link href="/dashboard" className="hover:text-blue-500">
                  Dashboard
                </Link>
                <Link href="/bookmarks" className="hover:text-blue-500">
                  Bookmarks
                </Link>
              </SignedIn>
              
              {/* Auth buttons */}
              <div className="flex gap-4">
                <SignedOut>
                  <SignInButton mode="modal">
                    <button className="hover:text-blue-500">Sign In</button>
                  </SignInButton>
                  <SignUpButton mode="modal">
                    <button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
                      Sign Up
                    </button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <UserButton afterSignOutUrl="/" />
                </SignedIn>
              </div>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}